name: Run Test

on:
  push:
    branches:
      - main
  merge_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: [SETUP] Checkout
        uses: actions/checkout@v3
      
      - name: [SETUP] Install Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      
      - name: [SETUP] Install dependencies
        run: yarn install

      - name: [TEST] Run tests
        run: yarn test

      - name: [TEST] Report tests
        if: success() || failure()
        with:
          name: test-results
          path: junit.xml
          fail-on-error: 'false'
          reporter: jest-junit
          token: ${{ secret.GITHUB_TOKEN }}
      
      - name: [TEST] Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secret.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`