name: Run Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test:report

      - name: Report tests
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-results
          path: junit.xml
          fail-on-error: 'false'
          reporter: jest-junit
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          # DISCORD_EMBEDS: '[{"title": "Pull request test result", "description": "[hyperlink](https://google.com) `see result`"}]'
        uses: Ilshidur/action-discord@0.3.2
        # with:
        #   args: 'The pull request {{ EVENT_PAYLOAD.repository.full_name }} has been tested.'
